development:
  adapter: postgresql
  database: branch_sinatra_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: branch_sinatra_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: branch_sinatra_production
  pool: 5
  timeout: 5000
